### ISSUE TITLE
Fuel model 504 Error

### ISSUE THREAD

**Issue by hilary-luo** [gazebo-web/fuel-server#19]
Hey folks! Hope you are all having a good day. We have noticed some issues with some Gazebo fuel models that are affecting the Turtlebot4 / Clearpath simulation worlds and are looking for some support. Attempts to download certain models are resulting in 504 responses. The errors seem to always occur for zip files being downloaded with [fuel.ignitionrobotics.org](http://fuel.ignitionrobotics.org/) links from within the models.

For example, including
```
<uri>
  https://fuel.gazebosim.org/1.0/OpenRobotics/models/Rescue Randy Sitting
</uri>
```
results in the following errors:
```
[ruby $(which ign) gazebo-1] [Err] [FuelClient.cc:717] Failed to download model.
[ruby $(which ign) gazebo-1]   Server: https://fuel.ignitionrobotics.org/
[ruby $(which ign) gazebo-1]   Route: openrobotics/models/artifact proximity detector/tip/artifact proximity detector.zip
[ruby $(which ign) gazebo-1]   REST response code: 504
[ruby $(which ign) gazebo-1] [Err] [Server.cc:139] Error Code 13: [/sdf/model[@name="rescue_randy_sitting"]/include[0]/uri:/home/hluo/.ignition/fuel/fuel.gazebosim.org/openrobotics/models/rescue randy sitting/8/model.sdf:L6]: Msg: Unable to find uri[https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/Artifact Proximity Detector]
```

Related to: https://github.com/clearpathrobotics/clearpath_simulator/issues/30

**Comment by nuclearsandwich** [comment]
@nkoenig can you take a look when you can and let us know if there's some infrastructure change we need to make?

**Comment by azeey** [comment]
I tried loading the following world:
```xml
<?xml version="1.0" ?>
<sdf version="1.6">
  <world name="default">
    <include>
      <uri> https://fuel.gazebosim.org/1.0/OpenRobotics/models/Rescue Randy Sitting</uri>
    </include>
  </world>
</sdf>
```

but I wasn't able to reproduce the error. What version of Gazebo are you using? Can you try again with this SDF?

**Comment by hilary-luo** [comment]
Funny how timing works. The 504 error issue seems to have cleared now, looks like the redirect is working and I am able to download those specific files again. I am just waiting for confirmation from some of our end users that it is also resolved for them and I will close this issue.

I appreciate you taking the time to look at this even if it resolved in this way.

**Comment by hilary-luo** [comment]
The issue seems to be present again this morning. A simpler way to represent the problem is that I picked out one of the files that is failing and I can't successfully use a wget command on it.

```
wget "https://fuel.ignitionrobotics.org/1.0/movai/models/pallet_box_mobile/tip/pallet_box_mobile.zip"
--2024-03-27 09:16:36--  https://fuel.ignitionrobotics.org/1.0/movai/models/pallet_box_mobile/tip/pallet_box_mobile.zip
Resolving fuel.ignitionrobotics.org (fuel.ignitionrobotics.org)... 54.159.86.60, 54.165.150.233
Connecting to fuel.ignitionrobotics.org (fuel.ignitionrobotics.org)|54.159.86.60|:443... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
Retrying.

--2024-03-27 09:17:38--  (try: 2)  https://fuel.ignitionrobotics.org/1.0/movai/models/pallet_box_mobile/tip/pallet_box_mobile.zip
Reusing existing connection to fuel.ignitionrobotics.org:443.
HTTP request sent, awaiting response... 504 Gateway Time-out
Retrying.
```

This was not working yesterday morning, but was working last night, no longer working now. 

Another Open Robotics contact has now mentioned a known recent issue with the latest release and redirects for ignition urls. In the face of this it does seem like this could be solved for our users if the fuel models were internally updated to all use the `gazebosim` links for any interdependencies rather than the deprecated `ignitionrobotics` links. If I update my links to all be the `gazebosim` links it is insufficient because of these interdependencies.
